### ISSUE TITLE
Home API 

### ISSUE THREAD

**Issue by ijustwannabeme** [Exit1ofYeouido/BackEnd#11]
## 💡 Feature Issue
Home API 구현

## 🌿  Tasks
- [x] HOME API
- [x] 토큰에서 회원 매핑
- [x] 한국투자증권 API 호출
- [ ] 토큰 만료 후 토큰 발급
- [x] 총 자산, 총 주식 보유 수, 총 포인트
- [ ] 브랜드 로고 (보류)

**Comment by ijustwannabeme** [comment]
소수점 두자릿수까지 ** 첫번째 멤버

![image](https://github.com/user-attachments/assets/39e70b10-bf1d-44a1-aa88-f31612fe7f24)

![image](https://github.com/user-attachments/assets/095ef8bb-8afc-469a-87f7-d62b0e9ede23)
