### ISSUE TITLE
관리자 검색 로그 확인 기능

### ISSUE THREAD

**Issue by LimSeHyeon** [Exit1ofYeouido/BackEnd#35]
## 💡 Feature Issue
관리자 페이지에서 검색 로그를 확인하는 기능을 추가합니다.

## 🌿  Tasks
- [ ] 카프카 메시지 수신해서 DB에 추가하기
- [ ] 검색 시마다 검색 로그에 저장하기
- [ ] 관리자 조회 API
