### ISSUE TITLE
Advertisement 광고 리워드 Api 작성

### ISSUE THREAD

**Issue by lemonticsoul** [Exit1ofYeouido/BackEnd#4]
## 💡 Feature Issue

광고 리워드를 작성하고, 이를 postman 통신까지 완료되어야합니다!

## 🌿  Tasks

- [x] 광고 의뢰한 기업목록 api 작성
- [x] Common 작성
- [x] 광고 영상 uri api 작성
- [x] 미디어 마다 quiz문제와 답 출력 api 작성
- [x] 퀴즈 맞추고 주식 제공 api 작성
- [x] 기업 세부정보 api 작성
- [x] 단일 테스트 
- [x] kafka 연결
- [x]  토큰 까서 memberID 매핑
- [x] 마무리
