### ISSUE TITLE
Attendance 보상 지급 로직 수정 및 예외처리

### ISSUE THREAD

**Issue by LimSeHyeon** [Exit1ofYeouido/BackEnd#43]
## 💡 Feature Issue
cgv(겹치는 이름) → cj cgv(종목 이름)
영수증 예외처리 - 이미 있는거 확인

## 🌿  Tasks
- [x] giveStockService getPrice 로직 매개변수 수정
- [x] cgv(겹치는 이름) → cj cgv(종목 이름)
- [x] 영수증 예외처리 - 이미 있는거 확인
- [x] 출석 보상 지급 시 종목 중복 조회 오류 수정
