### ISSUE TITLE
검색 로그 기록 및 관리자용 조회

### ISSUE THREAD

**Issue by LimSeHyeon** [Exit1ofYeouido/BackEnd#45]
## 💡 Feature Issue
사용자가 검색 로그를 남기고, 관리자가 조회할 수 있는 API 구현

## 🌿  Tasks
- [x] Kafka 이벤트 수신을 통한 보유 주식 정보 업데이트
- [x] 검색 api에 검색 로그 남기기 기능 추가
- [x] 멤버id, 주식 코드 받아서 검색기록 조회
- [x] 멤버id 받아서 검색기록 조회
