### ISSUE TITLE
Myservice API 추가 및 수정

### ISSUE THREAD

**Issue by subsub97** [Exit1ofYeouido/BackEnd#50]
## 💡 Feature Issue

판매 소수점 주식 등록 상태의 목록 수정 기능 추가하기
중복된 핸드폰 번호로 회원가입 요청 시 발생하는 에러 상세 설명으로 응답하기
온주와 소수점 주식 판매 분류하기
검색 로그 데이터 조회를 위한 관리자 권한 검증로직 추가

## 🌿  Tasks

- [x] 미체결 내역 조회 API
- [ ] 온주 판매 API
- [x] 중복 휴대폰 번호 가입 예외처리
- [x] 관리자 권한 검증 추가하기
