### ISSUE TITLE
보유 주식 api

### ISSUE THREAD

**Issue by subsub97** [Exit1ofYeouido/BackEnd#90]
## 💡 Feature Issue

my service api 리팩토링 및 수정

## 🌿  Tasks

- [x] 판매체결 히스토리 API 오류 수정
- [x]  보유수량 0개 보유시 조회되는 오류 수정
- [x]  1년단위 주간 차트 api 추가
